//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassMeta.DesktopApp.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PassMeta.DesktopApp.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ACCOUNT__FIRST_NAME_LABEL {
            get {
                return ResourceManager.GetString("ACCOUNT__FIRST_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string ACCOUNT__LAST_NAME_LABEL {
            get {
                return ResourceManager.GetString("ACCOUNT__LAST_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ACCOUNT__LOGIN_LABEL {
            get {
                return ResourceManager.GetString("ACCOUNT__LOGIN_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string ACCOUNT__PASSWORD_CONFIRM_LABEL {
            get {
                return ResourceManager.GetString("ACCOUNT__PASSWORD_CONFIRM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is missed!.
        /// </summary>
        public static string ACCOUNT__PASSWORD_CONFIRM_MISSED_WARN {
            get {
                return ResourceManager.GetString("ACCOUNT__PASSWORD_CONFIRM_MISSED_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ACCOUNT__PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("ACCOUNT__PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ACCOUNT__SAVE_BTN {
            get {
                return ResourceManager.GetString("ACCOUNT__SAVE_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data has been save successfully!.
        /// </summary>
        public static string ACCOUNT__SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("ACCOUNT__SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to sign out?.
        /// </summary>
        public static string ACCOUNT__SIGN_OUT_CONFIRM {
            get {
                return ResourceManager.GetString("ACCOUNT__SIGN_OUT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string ACCOUNT__TITLE {
            get {
                return ResourceManager.GetString("ACCOUNT__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection error!.
        /// </summary>
        public static string API__CONNECTION_ERR {
            get {
                return ResourceManager.GetString("API__CONNECTION_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timeout error!.
        /// </summary>
        public static string API__CONNECTION_TIMEOUT_ERR {
            get {
                return ResourceManager.GetString("API__CONNECTION_TIMEOUT_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access error!.
        /// </summary>
        public static string API__FORBIDDEN_ERR {
            get {
                return ResourceManager.GetString("API__FORBIDDEN_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error!.
        /// </summary>
        public static string API__INTERNAL_SERVER_ERR {
            get {
                return ResourceManager.GetString("API__INTERNAL_SERVER_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid server response!.
        /// </summary>
        public static string API__INVALID_RESPONSE_ERR {
            get {
                return ResourceManager.GetString("API__INVALID_RESPONSE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization error! Please, try re-login..
        /// </summary>
        public static string API__UNAUTHORIZED_ERR {
            get {
                return ResourceManager.GetString("API__UNAUTHORIZED_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect url! Please, check app settings..
        /// </summary>
        public static string API__URL_ERR {
            get {
                return ResourceManager.GetString("API__URL_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have uncommited changes, rollback and exit?.
        /// </summary>
        public static string APP__CONFIRM_ROLLBACK_ON_QUIT {
            get {
                return ResourceManager.GetString("APP__CONFIRM_ROLLBACK_ON_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string APP__OFFLINE_MODE {
            get {
                return ResourceManager.GetString("APP__OFFLINE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string APP__ONLINE_MODE {
            get {
                return ResourceManager.GetString("APP__ONLINE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application config file reading failed! Creating a new one....
        /// </summary>
        public static string APP_CONFIG__LOAD_ERR {
            get {
                return ResourceManager.GetString("APP_CONFIG__LOAD_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application config file saving error! (see logs).
        /// </summary>
        public static string APP_CONFIG__SAVE_ERR {
            get {
                return ResourceManager.GetString("APP_CONFIG__SAVE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data validation error!.
        /// </summary>
        public static string AUTH__DATA_VALIDATION_ERR {
            get {
                return ResourceManager.GetString("AUTH__DATA_VALIDATION_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string AUTH__LOGIN_PLACEHOLDER {
            get {
                return ResourceManager.GetString("AUTH__LOGIN_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AUTH__PASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("AUTH__PASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string AUTH__SIGN_IN_BTN {
            get {
                return ResourceManager.GetString("AUTH__SIGN_IN_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string AUTH__SIGN_UP_BTN {
            get {
                return ResourceManager.GetString("AUTH__SIGN_UP_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string AUTH__TITLE {
            get {
                return ResourceManager.GetString("AUTH__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to view.
        /// </summary>
        public static string AUTH_REQUIRED__TITLE {
            get {
                return ResourceManager.GetString("AUTH_REQUIRED__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DIALOG__BTN_CANCEL {
            get {
                return ResourceManager.GetString("DIALOG__BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DIALOG__BTN_CLOSE {
            get {
                return ResourceManager.GetString("DIALOG__BTN_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DIALOG__BTN_NO {
            get {
                return ResourceManager.GetString("DIALOG__BTN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string DIALOG__BTN_OK {
            get {
                return ResourceManager.GetString("DIALOG__BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DIALOG__BTN_YES {
            get {
                return ResourceManager.GetString("DIALOG__BTN_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input form.
        /// </summary>
        public static string DIALOG__DEFAULT_ASK_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_ASK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string DIALOG__DEFAULT_CONFIRM_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_CONFIRM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DIALOG__DEFAULT_ERROR_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string DIALOG__DEFAULT_FAILURE_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_FAILURE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string DIALOG__DEFAULT_INFO_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string DICT_ACCOUNT__FIRST_NAME {
            get {
                return ResourceManager.GetString("DICT_ACCOUNT__FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to surname.
        /// </summary>
        public static string DICT_ACCOUNT__LAST_NAME {
            get {
                return ResourceManager.GetString("DICT_ACCOUNT__LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string DICT_ACCOUNT__LOGIN {
            get {
                return ResourceManager.GetString("DICT_ACCOUNT__LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new password.
        /// </summary>
        public static string DICT_ACCOUNT__PASSWORD {
            get {
                return ResourceManager.GetString("DICT_ACCOUNT__PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current password (confirm).
        /// </summary>
        public static string DICT_ACCOUNT__PASSWORD_CONFIRM {
            get {
                return ResourceManager.GetString("DICT_ACCOUNT__PASSWORD_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string DICT_AUTH__USER {
            get {
                return ResourceManager.GetString("DICT_AUTH__USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account password.
        /// </summary>
        public static string DICT_STORAGE__CHECK_PASSWORD {
            get {
                return ResourceManager.GetString("DICT_STORAGE__CHECK_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passfile color.
        /// </summary>
        public static string DICT_STORAGE__PASSFILE_COLOR {
            get {
                return ResourceManager.GetString("DICT_STORAGE__PASSFILE_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timestamp of passfile creation.
        /// </summary>
        public static string DICT_STORAGE__PASSFILE_CREATED_ON {
            get {
                return ResourceManager.GetString("DICT_STORAGE__PASSFILE_CREATED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passfile ID.
        /// </summary>
        public static string DICT_STORAGE__PASSFILE_ID {
            get {
                return ResourceManager.GetString("DICT_STORAGE__PASSFILE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passfile name.
        /// </summary>
        public static string DICT_STORAGE__PASSFILE_NAME {
            get {
                return ResourceManager.GetString("DICT_STORAGE__PASSFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passfile data.
        /// </summary>
        public static string DICT_STORAGE__PASSFILE_SMTH {
            get {
                return ResourceManager.GetString("DICT_STORAGE__PASSFILE_SMTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string GENERATOR__BTN {
            get {
                return ResourceManager.GetString("GENERATOR__BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy password.
        /// </summary>
        public static string GENERATOR__COPY_BTN {
            get {
                return ResourceManager.GetString("GENERATOR__COPY_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string GENERATOR__INCLUDE_DIGITS {
            get {
                return ResourceManager.GetString("GENERATOR__INCLUDE_DIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spec. symbols.
        /// </summary>
        public static string GENERATOR__INCLUDE_SPECIAL {
            get {
                return ResourceManager.GetString("GENERATOR__INCLUDE_SPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string GENERATOR__PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("GENERATOR__PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is copied to clipboard.
        /// </summary>
        public static string GENERATOR__RESULT_COPIED {
            get {
                return ResourceManager.GetString("GENERATOR__RESULT_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password generator.
        /// </summary>
        public static string GENERATOR__TITLE {
            get {
                return ResourceManager.GetString("GENERATOR__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LANG__EN {
            get {
                return ResourceManager.GetString("LANG__EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string LANG__RU {
            get {
                return ResourceManager.GetString("LANG__RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string MAIN_MENU__ACCOUNT_BTN {
            get {
                return ResourceManager.GetString("MAIN_MENU__ACCOUNT_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        public static string MAIN_MENU__GENERATOR_BTN {
            get {
                return ResourceManager.GetString("MAIN_MENU__GENERATOR_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MAIN_MENU__SETTINGS_BTN {
            get {
                return ResourceManager.GetString("MAIN_MENU__SETTINGS_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string MAIN_MENU__STORAGE_BTN {
            get {
                return ResourceManager.GetString("MAIN_MENU__STORAGE_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed.
        /// </summary>
        public static string OKBAD_MORE__ALLOWED {
            get {
                return ResourceManager.GetString("OKBAD_MORE__ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disallowed.
        /// </summary>
        public static string OKBAD_MORE__DISALLOWED {
            get {
                return ResourceManager.GetString("OKBAD_MORE__DISALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info: .
        /// </summary>
        public static string OKBAD_MORE__INFO {
            get {
                return ResourceManager.GetString("OKBAD_MORE__INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max allowed.
        /// </summary>
        public static string OKBAD_MORE__MAX_ALLOWED {
            get {
                return ResourceManager.GetString("OKBAD_MORE__MAX_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min allowed.
        /// </summary>
        public static string OKBAD_MORE__MIN_ALLOWED {
            get {
                return ResourceManager.GetString("OKBAD_MORE__MIN_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string OKBAD_MORE__REQUIRED {
            get {
                return ResourceManager.GetString("OKBAD_MORE__REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, input your account password to delete passfile &apos;{0}&apos; from the server (#{1}, deleted locally on {2}).
        /// </summary>
        public static string PASSERVICE__ASK_PASSWORD_TO_DELETE_PASSFILE {
            get {
                return ResourceManager.GetString("PASSERVICE__ASK_PASSWORD_TO_DELETE_PASSFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved!.
        /// </summary>
        public static string PASSERVICE__SUCCESS_COMMIT {
            get {
                return ResourceManager.GetString("PASSERVICE__SUCCESS_COMMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input NEW passphrase.
        /// </summary>
        public static string PASSFILE__ASK_NEW_PASSPHRASE {
            get {
                return ResourceManager.GetString("PASSFILE__ASK_NEW_PASSPHRASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input passphrase.
        /// </summary>
        public static string PASSFILE__ASK_PASSPHRASE {
            get {
                return ResourceManager.GetString("PASSFILE__ASK_PASSPHRASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string PASSFILE__BTN_CHANGE_PWD {
            get {
                return ResourceManager.GetString("PASSFILE__BTN_CHANGE_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string PASSFILE__BTN_DELETE {
            get {
                return ResourceManager.GetString("PASSFILE__BTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve conflicts....
        /// </summary>
        public static string PASSFILE__BTN_MERGE {
            get {
                return ResourceManager.GetString("PASSFILE__BTN_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string PASSFILE__BTN_OK {
            get {
                return ResourceManager.GetString("PASSFILE__BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string PASSFILE__BTN_RESTORE {
            get {
                return ResourceManager.GetString("PASSFILE__BTN_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PASSFILE__BTN_SAVE {
            get {
                return ResourceManager.GetString("PASSFILE__BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete passfile &apos;{0}&apos; #{1}?.
        /// </summary>
        public static string PASSFILE__CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("PASSFILE__CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile decryption failed.
        /// </summary>
        public static string PASSFILE__DECRYPTION_ERROR {
            get {
                return ResourceManager.GetString("PASSFILE__DECRYPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile encryption failed.
        /// </summary>
        public static string PASSFILE__ENCRYPTION_ERROR {
            get {
                return ResourceManager.GetString("PASSFILE__ENCRYPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name!.
        /// </summary>
        public static string PASSFILE__INCORRECT_NAME {
            get {
                return ResourceManager.GetString("PASSFILE__INCORRECT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase successfully changed!.
        /// </summary>
        public static string PASSFILE__INFO_PASSPHRASE_CHANGED {
            get {
                return ResourceManager.GetString("PASSFILE__INFO_PASSPHRASE_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed:.
        /// </summary>
        public static string PASSFILE__LABEL_CHANGED_ON {
            get {
                return ResourceManager.GetString("PASSFILE__LABEL_CHANGED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string PASSFILE__LABEL_COLOR {
            get {
                return ResourceManager.GetString("PASSFILE__LABEL_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        public static string PASSFILE__LABEL_CREATED_ON {
            get {
                return ResourceManager.GetString("PASSFILE__LABEL_CREATED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string PASSFILE__LABEL_NAME {
            get {
                return ResourceManager.GetString("PASSFILE__LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        public static string PASSFILE__LABEL_STATE {
            get {
                return ResourceManager.GetString("PASSFILE__LABEL_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed locally ({0}).
        /// </summary>
        public static string PASSFILE__STATE_LOCAL_CHANGED {
            get {
                return ResourceManager.GetString("PASSFILE__STATE_LOCAL_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New (local, {0}).
        /// </summary>
        public static string PASSFILE__STATE_LOCAL_CREATED {
            get {
                return ResourceManager.GetString("PASSFILE__STATE_LOCAL_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted locally ({0}).
        /// </summary>
        public static string PASSFILE__STATE_LOCAL_DELETED {
            get {
                return ResourceManager.GetString("PASSFILE__STATE_LOCAL_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string PASSFILE__STATE_OK {
            get {
                return ResourceManager.GetString("PASSFILE__STATE_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile &apos;{0}&apos; (#{1}).
        /// </summary>
        public static string PASSFILE__TITLE {
            get {
                return ResourceManager.GetString("PASSFILE__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted locally passfile &apos;{0}&apos; (#{1}).
        /// </summary>
        public static string PASSFILE__TITLE_DELETED {
            get {
                return ResourceManager.GetString("PASSFILE__TITLE_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passfile &apos;{0}&apos;.
        /// </summary>
        public static string PASSFILE__TITLE_NEW {
            get {
                return ResourceManager.GetString("PASSFILE__TITLE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong passphrase!.
        /// </summary>
        public static string PASSFILE__WRONG_PASSPHRASE {
            get {
                return ResourceManager.GetString("PASSFILE__WRONG_PASSPHRASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string PASSFILE_COLOR__BLUE {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string PASSFILE_COLOR__GREEN {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__GREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey.
        /// </summary>
        public static string PASSFILE_COLOR__GREY {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__GREY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string PASSFILE_COLOR__ORANGE {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__ORANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string PASSFILE_COLOR__PINK {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__PINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string PASSFILE_COLOR__PURPLE {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__PURPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string PASSFILE_COLOR__RED {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        public static string PASSFILE_COLOR__TEAL {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__TEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string PASSFILE_COLOR__YELLOW {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__YELLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading error.
        /// </summary>
        public static string PASSFILE_PROBLEM__DOWNLOAD_ERR {
            get {
                return ResourceManager.GetString("PASSFILE_PROBLEM__DOWNLOAD_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs merge.
        /// </summary>
        public static string PASSFILE_PROBLEM__NEEDS_MERGE {
            get {
                return ResourceManager.GetString("PASSFILE_PROBLEM__NEEDS_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PASSFILE_PROBLEM__OTHER {
            get {
                return ResourceManager.GetString("PASSFILE_PROBLEM__OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote deleting error.
        /// </summary>
        public static string PASSFILE_PROBLEM__REMOTE_DELETING_ERR {
            get {
                return ResourceManager.GetString("PASSFILE_PROBLEM__REMOTE_DELETING_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading error.
        /// </summary>
        public static string PASSFILE_PROBLEM__UPLOAD_ERR {
            get {
                return ResourceManager.GetString("PASSFILE_PROBLEM__UPLOAD_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfiles are saved to the local storage with errors! (see logs).
        /// </summary>
        public static string PASSMANAGER__COMMIT_WARNING {
            get {
                return ResourceManager.GetString("PASSMANAGER__COMMIT_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string PASSMANAGER__DEFAULT_NEW_PASSFILE_NAME {
            get {
                return ResourceManager.GetString("PASSMANAGER__DEFAULT_NEW_PASSFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile local manager error! (see logs).
        /// </summary>
        public static string PASSMANAGER__ERR {
            get {
                return ResourceManager.GetString("PASSMANAGER__ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile local version not found!.
        /// </summary>
        public static string PASSMANAGER__VERSION_NOT_FOUND_ERR {
            get {
                return ResourceManager.GetString("PASSMANAGER__VERSION_NOT_FOUND_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is incorrect!.
        /// </summary>
        public static string SETTINGS__INCORRECT_API {
            get {
                return ResourceManager.GetString("SETTINGS__INCORRECT_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SETTINGS__LOCALIZATION {
            get {
                return ResourceManager.GetString("SETTINGS__LOCALIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SETTINGS__SAVE_BTN {
            get {
                return ResourceManager.GetString("SETTINGS__SAVE_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings have been saved successfully!.
        /// </summary>
        public static string SETTINGS__SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("SETTINGS__SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS__TITLE {
            get {
                return ResourceManager.GetString("SETTINGS__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input passphrase for a new passfile.
        /// </summary>
        public static string STORAGE__ASK_PASSPHRASE_FOR_NEW_PASSFILE {
            get {
                return ResourceManager.GetString("STORAGE__ASK_PASSPHRASE_FOR_NEW_PASSFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete section &apos;{0}&apos;?.
        /// </summary>
        public static string STORAGE__CONFIRM_DELETE_SECTION {
            get {
                return ResourceManager.GetString("STORAGE__CONFIRM_DELETE_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback current changes?.
        /// </summary>
        public static string STORAGE__CONFIRM_ROLLBACK {
            get {
                return ResourceManager.GetString("STORAGE__CONFIRM_ROLLBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string STORAGE__CONTEXT_DELETE {
            get {
                return ResourceManager.GetString("STORAGE__CONTEXT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string STORAGE__CONTEXT_EDIT {
            get {
                return ResourceManager.GetString("STORAGE__CONTEXT_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string STORAGE__ITEM_PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("STORAGE__ITEM_PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string STORAGE__ITEM_WHAT_LABEL {
            get {
                return ResourceManager.GetString("STORAGE__ITEM_WHAT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy 1st.
        /// </summary>
        public static string STORAGE__LOGIN_COPY {
            get {
                return ResourceManager.GetString("STORAGE__LOGIN_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New section.
        /// </summary>
        public static string STORAGE__NEW_SECTION_NAME {
            get {
                return ResourceManager.GetString("STORAGE__NEW_SECTION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        public static string STORAGE__NO_ITEMS {
            get {
                return ResourceManager.GetString("STORAGE__NO_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sections.
        /// </summary>
        public static string STORAGE__NO_SECTIONS {
            get {
                return ResourceManager.GetString("STORAGE__NO_SECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found,
        ///try another keywords....
        /// </summary>
        public static string STORAGE__NO_SECTIONS_FOUND {
            get {
                return ResourceManager.GetString("STORAGE__NO_SECTIONS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string STORAGE__PASSFILES_TITLE {
            get {
                return ResourceManager.GetString("STORAGE__PASSFILES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is copied to clipboard.
        /// </summary>
        public static string STORAGE__PASSWORD_COPIED {
            get {
                return ResourceManager.GetString("STORAGE__PASSWORD_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string STORAGE__PASSWORD_COPY {
            get {
                return ResourceManager.GetString("STORAGE__PASSWORD_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search passwords....
        /// </summary>
        public static string STORAGE__SECTION_SEARCH_INPUT_WATERMARK {
            get {
                return ResourceManager.GetString("STORAGE__SECTION_SEARCH_INPUT_WATERMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add password.
        /// </summary>
        public static string STORAGE__TOOLTIP_ADD_ITEM {
            get {
                return ResourceManager.GetString("STORAGE__TOOLTIP_ADD_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add passfile.
        /// </summary>
        public static string STORAGE__TOOLTIP_ADD_PASSFILE {
            get {
                return ResourceManager.GetString("STORAGE__TOOLTIP_ADD_PASSFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add section.
        /// </summary>
        public static string STORAGE__TOOLTIP_ADD_SECTION {
            get {
                return ResourceManager.GetString("STORAGE__TOOLTIP_ADD_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login &apos;{0}&apos; is copied to clipboard.
        /// </summary>
        public static string STORAGE__WHAT_COPIED {
            get {
                return ResourceManager.GetString("STORAGE__WHAT_COPIED", resourceCulture);
            }
        }
    }
}
