//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassMeta.DesktopApp.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PassMeta.DesktopApp.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ACCOUNT__FIRST_NAME_LABEL {
            get {
                return ResourceManager.GetString("ACCOUNT__FIRST_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string ACCOUNT__LAST_NAME_LABEL {
            get {
                return ResourceManager.GetString("ACCOUNT__LAST_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ACCOUNT__LOGIN_LABEL {
            get {
                return ResourceManager.GetString("ACCOUNT__LOGIN_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string ACCOUNT__PASSWORD_CONFIRM_LABEL {
            get {
                return ResourceManager.GetString("ACCOUNT__PASSWORD_CONFIRM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ACCOUNT__PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("ACCOUNT__PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ACCOUNT__SAVE_BTN {
            get {
                return ResourceManager.GetString("ACCOUNT__SAVE_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data has been save successfully!.
        /// </summary>
        public static string ACCOUNT__SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("ACCOUNT__SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string ACCOUNT__SIGN_OUT_BTN {
            get {
                return ResourceManager.GetString("ACCOUNT__SIGN_OUT_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to sign out?.
        /// </summary>
        public static string ACCOUNT__SIGN_OUT_CONFIRM {
            get {
                return ResourceManager.GetString("ACCOUNT__SIGN_OUT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string ACCOUNT__TITLE {
            get {
                return ResourceManager.GetString("ACCOUNT__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input your passphrase.
        /// </summary>
        public static string ASK__PASSPHRASE {
            get {
                return ResourceManager.GetString("ASK__PASSPHRASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string AUTH__LOGIN_PLACEHOLDER {
            get {
                return ResourceManager.GetString("AUTH__LOGIN_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AUTH__PASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("AUTH__PASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string AUTH__SIGN_IN_BTN {
            get {
                return ResourceManager.GetString("AUTH__SIGN_IN_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string AUTH__SIGN_UP_BTN {
            get {
                return ResourceManager.GetString("AUTH__SIGN_UP_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string AUTH__TITLE {
            get {
                return ResourceManager.GetString("AUTH__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize to view this page.
        /// </summary>
        public static string AUTH_REQUIRED__TITLE {
            get {
                return ResourceManager.GetString("AUTH_REQUIRED__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DIALOG__BTN_CANCEL {
            get {
                return ResourceManager.GetString("DIALOG__BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DIALOG__BTN_CLOSE {
            get {
                return ResourceManager.GetString("DIALOG__BTN_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DIALOG__BTN_NO {
            get {
                return ResourceManager.GetString("DIALOG__BTN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string DIALOG__BTN_OK {
            get {
                return ResourceManager.GetString("DIALOG__BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DIALOG__BTN_YES {
            get {
                return ResourceManager.GetString("DIALOG__BTN_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input form.
        /// </summary>
        public static string DIALOG__DEFAULT_ASK_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_ASK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string DIALOG__DEFAULT_CONFIRM_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_CONFIRM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DIALOG__DEFAULT_ERROR_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string DIALOG__DEFAULT_FAILURE_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_FAILURE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string DIALOG__DEFAULT_INFO_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file reading failed! Creating a new one....
        /// </summary>
        public static string ERR__CONFIG_LOAD {
            get {
                return ResourceManager.GetString("ERR__CONFIG_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file saving error!.
        /// </summary>
        public static string ERR__CONFIG_SAVE {
            get {
                return ResourceManager.GetString("ERR__CONFIG_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection error!.
        /// </summary>
        public static string ERR__CONNECTION_FAILURE {
            get {
                return ResourceManager.GetString("ERR__CONNECTION_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timeout error!.
        /// </summary>
        public static string ERR__CONNECTION_TIMEOUT {
            get {
                return ResourceManager.GetString("ERR__CONNECTION_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data validation error!.
        /// </summary>
        public static string ERR__DATA_VALIDATION {
            get {
                return ResourceManager.GetString("ERR__DATA_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access error!.
        /// </summary>
        public static string ERR__HTTP_FORBIDDEN {
            get {
                return ResourceManager.GetString("ERR__HTTP_FORBIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error!.
        /// </summary>
        public static string ERR__HTTP_INTERNAL_SERVER {
            get {
                return ResourceManager.GetString("ERR__HTTP_INTERNAL_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization error! Please, try re-login..
        /// </summary>
        public static string ERR__HTTP_UNAUTHORIZED {
            get {
                return ResourceManager.GetString("ERR__HTTP_UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid server response!.
        /// </summary>
        public static string ERR__INVALID_API_RESPONSE {
            get {
                return ResourceManager.GetString("ERR__INVALID_API_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid passfile found on disk! Delete it?.
        /// </summary>
        public static string ERR__INVALID_PASSFILE_FOUND {
            get {
                return ResourceManager.GetString("ERR__INVALID_PASSFILE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile &apos;{0}&apos; remote archiving error!.
        /// </summary>
        public static string ERR__PASSFILE_ARCHIVE_REMOTE {
            get {
                return ResourceManager.GetString("ERR__PASSFILE_ARCHIVE_REMOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is wrong (file decryption failed).
        /// </summary>
        public static string ERR__PASSFILE_DECRYPTION {
            get {
                return ResourceManager.GetString("ERR__PASSFILE_DECRYPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile &apos;{0}&apos; local deleting error!.
        /// </summary>
        public static string ERR__PASSFILE_DELETE_LOCAL {
            get {
                return ResourceManager.GetString("ERR__PASSFILE_DELETE_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile &apos;{0}&apos; remote delete error!.
        /// </summary>
        public static string ERR__PASSFILE_DELETE_REMOTE {
            get {
                return ResourceManager.GetString("ERR__PASSFILE_DELETE_REMOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile &apos;{0}&apos; local saving error!.
        /// </summary>
        public static string ERR__PASSFILE_SAVE_LOCAL {
            get {
                return ResourceManager.GetString("ERR__PASSFILE_SAVE_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile &apos;{0}&apos; remote saving error!.
        /// </summary>
        public static string ERR__PASSFILE_SAVE_REMOTE {
            get {
                return ResourceManager.GetString("ERR__PASSFILE_SAVE_REMOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile &apos;{0}&apos; remote unarchive error!.
        /// </summary>
        public static string ERR__PASSFILE_UNARCHIVE_REMOTE {
            get {
                return ResourceManager.GetString("ERR__PASSFILE_UNARCHIVE_REMOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfiles reading error!.
        /// </summary>
        public static string ERR__PASSFILES_READ {
            get {
                return ResourceManager.GetString("ERR__PASSFILES_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect url! Please, check app settings..
        /// </summary>
        public static string ERR__URL {
            get {
                return ResourceManager.GetString("ERR__URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string GENERATOR__BTN {
            get {
                return ResourceManager.GetString("GENERATOR__BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string GENERATOR__INCLUDE_DIGITS {
            get {
                return ResourceManager.GetString("GENERATOR__INCLUDE_DIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spec. symbols.
        /// </summary>
        public static string GENERATOR__INCLUDE_SPECIAL {
            get {
                return ResourceManager.GetString("GENERATOR__INCLUDE_SPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string GENERATOR__PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("GENERATOR__PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password generator.
        /// </summary>
        public static string GENERATOR__TITLE {
            get {
                return ResourceManager.GetString("GENERATOR__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local mode.
        /// </summary>
        public static string INFO__PASSFILES_LOCAL_MODE {
            get {
                return ResourceManager.GetString("INFO__PASSFILES_LOCAL_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defferent versions of passfile &apos;{0}&apos; (&apos;{1}&apos;) have been merged.
        /// </summary>
        public static string INFO__PASSFILES_MERGED {
            get {
                return ResourceManager.GetString("INFO__PASSFILES_MERGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LANG__EN {
            get {
                return ResourceManager.GetString("LANG__EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string LANG__RU {
            get {
                return ResourceManager.GetString("LANG__RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string MAIN_MENU__ACCOUNT_BTN {
            get {
                return ResourceManager.GetString("MAIN_MENU__ACCOUNT_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        public static string MAIN_MENU__GENERATOR_BTN {
            get {
                return ResourceManager.GetString("MAIN_MENU__GENERATOR_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MAIN_MENU__SETTINGS_BTN {
            get {
                return ResourceManager.GetString("MAIN_MENU__SETTINGS_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string MAIN_MENU__STORAGE_BTN {
            get {
                return ResourceManager.GetString("MAIN_MENU__STORAGE_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed.
        /// </summary>
        public static string OKBAD_MORE__ALLOWED {
            get {
                return ResourceManager.GetString("OKBAD_MORE__ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disallowed.
        /// </summary>
        public static string OKBAD_MORE__DISALLOWED {
            get {
                return ResourceManager.GetString("OKBAD_MORE__DISALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info: .
        /// </summary>
        public static string OKBAD_MORE__INFO {
            get {
                return ResourceManager.GetString("OKBAD_MORE__INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max allowed.
        /// </summary>
        public static string OKBAD_MORE__MAX_ALLOWED {
            get {
                return ResourceManager.GetString("OKBAD_MORE__MAX_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min allowed.
        /// </summary>
        public static string OKBAD_MORE__MIN_ALLOWED {
            get {
                return ResourceManager.GetString("OKBAD_MORE__MIN_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string OKBAD_MORE__REQUIRED {
            get {
                return ResourceManager.GetString("OKBAD_MORE__REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is incorrect!.
        /// </summary>
        public static string SETTINGS__INCORRECT_API {
            get {
                return ResourceManager.GetString("SETTINGS__INCORRECT_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SETTINGS__LOCALIZATION {
            get {
                return ResourceManager.GetString("SETTINGS__LOCALIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SETTINGS__SAVE_BTN {
            get {
                return ResourceManager.GetString("SETTINGS__SAVE_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings have been saved successfully!.
        /// </summary>
        public static string SETTINGS__SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("SETTINGS__SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS__TITLE {
            get {
                return ResourceManager.GetString("SETTINGS__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string STORAGE__CONTEXT_ARCHIVE {
            get {
                return ResourceManager.GetString("STORAGE__CONTEXT_ARCHIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string STORAGE__CONTEXT_DELETE {
            get {
                return ResourceManager.GetString("STORAGE__CONTEXT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string STORAGE__CONTEXT_RENAME {
            get {
                return ResourceManager.GetString("STORAGE__CONTEXT_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        public static string STORAGE__NO_ITEMS {
            get {
                return ResourceManager.GetString("STORAGE__NO_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sections.
        /// </summary>
        public static string STORAGE__NO_SECTIONS {
            get {
                return ResourceManager.GetString("STORAGE__NO_SECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string STORAGE__PASSFILES_TITLE {
            get {
                return ResourceManager.GetString("STORAGE__PASSFILES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords.
        /// </summary>
        public static string STORAGE__PASSWORDS_TITLE {
            get {
                return ResourceManager.GetString("STORAGE__PASSWORDS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is missed!.
        /// </summary>
        public static string WARN__PASSWORD_CONFIRM_MISSED {
            get {
                return ResourceManager.GetString("WARN__PASSWORD_CONFIRM_MISSED", resourceCulture);
            }
        }
    }
}
