//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassMeta.DesktopApp.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PassMeta.DesktopApp.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ACCOUNT__FULL_NAME_LABEL {
            get {
                return ResourceManager.GetString("ACCOUNT__FULL_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ACCOUNT__LOGIN_LABEL {
            get {
                return ResourceManager.GetString("ACCOUNT__LOGIN_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string ACCOUNT__PASSWORD_CONFIRM_LABEL {
            get {
                return ResourceManager.GetString("ACCOUNT__PASSWORD_CONFIRM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ACCOUNT__PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("ACCOUNT__PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all sessions except the current one?.
        /// </summary>
        public static string ACCOUNT__RESET_SESSIONS_CONFIRM {
            get {
                return ResourceManager.GetString("ACCOUNT__RESET_SESSIONS_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions have been successfully reset!.
        /// </summary>
        public static string ACCOUNT__RESET_SESSIONS_SUCCESS {
            get {
                return ResourceManager.GetString("ACCOUNT__RESET_SESSIONS_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ACCOUNT__SAVE_BTN {
            get {
                return ResourceManager.GetString("ACCOUNT__SAVE_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data has been successfully save!.
        /// </summary>
        public static string ACCOUNT__SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("ACCOUNT__SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to sign out?.
        /// </summary>
        public static string ACCOUNT__SIGN_OUT_CONFIRM {
            get {
                return ResourceManager.GetString("ACCOUNT__SIGN_OUT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string ACCOUNT__TITLE {
            get {
                return ResourceManager.GetString("ACCOUNT__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all sessions.
        /// </summary>
        public static string ACCOUNT__TOOLTIP_RESET_SESSIONS {
            get {
                return ResourceManager.GetString("ACCOUNT__TOOLTIP_RESET_SESSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string ACCOUNT__TOOLTIP_SIGN_OUT {
            get {
                return ResourceManager.GetString("ACCOUNT__TOOLTIP_SIGN_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection error!.
        /// </summary>
        public static string API__CONNECTION_ERR {
            get {
                return ResourceManager.GetString("API__CONNECTION_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timeout error!.
        /// </summary>
        public static string API__CONNECTION_TIMEOUT_ERR {
            get {
                return ResourceManager.GetString("API__CONNECTION_TIMEOUT_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect url! Please, check app settings..
        /// </summary>
        public static string API__URL_ERR {
            get {
                return ResourceManager.GetString("API__URL_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have uncommited changes, rollback and exit?.
        /// </summary>
        public static string APP__CONFIRM_ROLLBACK_ON_QUIT {
            get {
                return ResourceManager.GetString("APP__CONFIRM_ROLLBACK_ON_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string APP__MENU_BTN__ACCOUNT {
            get {
                return ResourceManager.GetString("APP__MENU_BTN__ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        public static string APP__MENU_BTN__GENERATOR {
            get {
                return ResourceManager.GetString("APP__MENU_BTN__GENERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string APP__MENU_BTN__JOURNAL {
            get {
                return ResourceManager.GetString("APP__MENU_BTN__JOURNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string APP__MENU_BTN__LOGS {
            get {
                return ResourceManager.GetString("APP__MENU_BTN__LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string APP__MENU_BTN__SETTINGS {
            get {
                return ResourceManager.GetString("APP__MENU_BTN__SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string APP__MENU_BTN__STORAGE {
            get {
                return ResourceManager.GetString("APP__MENU_BTN__STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string APP__OFFLINE_MODE {
            get {
                return ResourceManager.GetString("APP__OFFLINE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string APP__ONLINE_MODE {
            get {
                return ResourceManager.GetString("APP__ONLINE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string APP__RIGHT_BAR_BTN__REFRESH {
            get {
                return ResourceManager.GetString("APP__RIGHT_BAR_BTN__REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application config file saving error! (see logs).
        /// </summary>
        public static string APP_CONFIG__SAVE_ERR {
            get {
                return ResourceManager.GetString("APP_CONFIG__SAVE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About PassMeta DesktopApp.
        /// </summary>
        public static string APP_INFO__TITLE {
            get {
                return ResourceManager.GetString("APP_INFO__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string APP_INFO__VERSION {
            get {
                return ResourceManager.GetString("APP_INFO__VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data validation error!.
        /// </summary>
        public static string AUTH__DATA_VALIDATION_ERR {
            get {
                return ResourceManager.GetString("AUTH__DATA_VALIDATION_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string AUTH__LOGIN_PLACEHOLDER {
            get {
                return ResourceManager.GetString("AUTH__LOGIN_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AUTH__PASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("AUTH__PASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string AUTH__SIGN_IN_BTN {
            get {
                return ResourceManager.GetString("AUTH__SIGN_IN_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string AUTH__SIGN_UP_BTN {
            get {
                return ResourceManager.GetString("AUTH__SIGN_UP_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string AUTH__TITLE {
            get {
                return ResourceManager.GetString("AUTH__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to view.
        /// </summary>
        public static string AUTH_REQUIRED__TITLE {
            get {
                return ResourceManager.GetString("AUTH_REQUIRED__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard error! (see logs).
        /// </summary>
        public static string CLIPBOARD__UNKNOWN_ERR {
            get {
                return ResourceManager.GetString("CLIPBOARD__UNKNOWN_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DIALOG__BTN_CANCEL {
            get {
                return ResourceManager.GetString("DIALOG__BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DIALOG__BTN_CLOSE {
            get {
                return ResourceManager.GetString("DIALOG__BTN_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DIALOG__BTN_NO {
            get {
                return ResourceManager.GetString("DIALOG__BTN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string DIALOG__BTN_OK {
            get {
                return ResourceManager.GetString("DIALOG__BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DIALOG__BTN_YES {
            get {
                return ResourceManager.GetString("DIALOG__BTN_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input form.
        /// </summary>
        public static string DIALOG__DEFAULT_ASK_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_ASK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string DIALOG__DEFAULT_CONFIRM_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_CONFIRM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DIALOG__DEFAULT_ERROR_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string DIALOG__DEFAULT_FAILURE_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_FAILURE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string DIALOG__DEFAULT_INFO_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DIALOG__DEFAULT_WARNING_TITLE {
            get {
                return ResourceManager.GetString("DIALOG__DEFAULT_WARNING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a password.
        /// </summary>
        public static string GENERATOR__BTN {
            get {
                return ResourceManager.GetString("GENERATOR__BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy password.
        /// </summary>
        public static string GENERATOR__COPY_BTN {
            get {
                return ResourceManager.GetString("GENERATOR__COPY_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string GENERATOR__INCLUDE_DIGITS {
            get {
                return ResourceManager.GetString("GENERATOR__INCLUDE_DIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters.
        /// </summary>
        public static string GENERATOR__INCLUDE_LETTERS {
            get {
                return ResourceManager.GetString("GENERATOR__INCLUDE_LETTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase.
        /// </summary>
        public static string GENERATOR__INCLUDE_LOWERCASE {
            get {
                return ResourceManager.GetString("GENERATOR__INCLUDE_LOWERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spec. symbols.
        /// </summary>
        public static string GENERATOR__INCLUDE_SPECIAL {
            get {
                return ResourceManager.GetString("GENERATOR__INCLUDE_SPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase.
        /// </summary>
        public static string GENERATOR__INCLUDE_UPPERCASE {
            get {
                return ResourceManager.GetString("GENERATOR__INCLUDE_UPPERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string GENERATOR__PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("GENERATOR__PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is copied to clipboard.
        /// </summary>
        public static string GENERATOR__RESULT_COPIED {
            get {
                return ResourceManager.GetString("GENERATOR__RESULT_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password generator.
        /// </summary>
        public static string GENERATOR__TITLE {
            get {
                return ResourceManager.GetString("GENERATOR__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string JOURNAL__ALL_KINDS {
            get {
                return ResourceManager.GetString("JOURNAL__ALL_KINDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string JOURNAL__HEADER_KIND {
            get {
                return ResourceManager.GetString("JOURNAL__HEADER_KIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string JOURNAL__HEADER_LOGIN {
            get {
                return ResourceManager.GetString("JOURNAL__HEADER_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string JOURNAL__HEADER_MORE {
            get {
                return ResourceManager.GetString("JOURNAL__HEADER_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; time.
        /// </summary>
        public static string JOURNAL__HEADER_TIMESTAMP {
            get {
                return ResourceManager.GetString("JOURNAL__HEADER_TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event type.
        /// </summary>
        public static string JOURNAL__TOOLTIP_KIND {
            get {
                return ResourceManager.GetString("JOURNAL__TOOLTIP_KIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string JOURNAL__TOOLTIP_MONTH {
            get {
                return ResourceManager.GetString("JOURNAL__TOOLTIP_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number.
        /// </summary>
        public static string JOURNAL__TOOLTIP_PAGE_NUM {
            get {
                return ResourceManager.GetString("JOURNAL__TOOLTIP_PAGE_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LANG__EN {
            get {
                return ResourceManager.GetString("LANG__EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string LANG__RU {
            get {
                return ResourceManager.GetString("LANG__RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string LOG_SECTION__ERROR {
            get {
                return ResourceManager.GetString("LOG_SECTION__ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERR.
        /// </summary>
        public static string LOG_SECTION__ERROR_SHORT {
            get {
                return ResourceManager.GetString("LOG_SECTION__ERROR_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string LOG_SECTION__INFO {
            get {
                return ResourceManager.GetString("LOG_SECTION__INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO.
        /// </summary>
        public static string LOG_SECTION__INFO_SHORT {
            get {
                return ResourceManager.GetString("LOG_SECTION__INFO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string LOG_SECTION__UNKNOWN {
            get {
                return ResourceManager.GetString("LOG_SECTION__UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string LOG_SECTION__UNKNOWN_SHORT {
            get {
                return ResourceManager.GetString("LOG_SECTION__UNKNOWN_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string LOG_SECTION__WARN {
            get {
                return ResourceManager.GetString("LOG_SECTION__WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARN.
        /// </summary>
        public static string LOG_SECTION__WARN_SHORT {
            get {
                return ResourceManager.GetString("LOG_SECTION__WARN_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid period selected!.
        /// </summary>
        public static string LOGS__INCORRECT_PERIOD_LABEL {
            get {
                return ResourceManager.GetString("LOGS__INCORRECT_PERIOD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing....
        /// </summary>
        public static string LOGS__NOT_FOUND_LABEL {
            get {
                return ResourceManager.GetString("LOGS__NOT_FOUND_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs period (start).
        /// </summary>
        public static string LOGS__TOOLTIP_DATE_FROM {
            get {
                return ResourceManager.GetString("LOGS__TOOLTIP_DATE_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs period (end).
        /// </summary>
        public static string LOGS__TOOLTIP_DATE_TO {
            get {
                return ResourceManager.GetString("LOGS__TOOLTIP_DATE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string PASSCONTEXT__DEFAULT_NEW_PASSFILE_NAME {
            get {
                return ResourceManager.GetString("PASSCONTEXT__DEFAULT_NEW_PASSFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile context manager error (see logs).
        /// </summary>
        public static string PASSCONTEXT__ERR_OTHER {
            get {
                return ResourceManager.GetString("PASSCONTEXT__ERR_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved locally.
        /// </summary>
        public static string PASSCONTEXT__INFO_COMMITED {
            get {
                return ResourceManager.GetString("PASSCONTEXT__INFO_COMMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error is occured in passfile service (see logs).
        /// </summary>
        public static string PASSERVICE__ERR {
            get {
                return ResourceManager.GetString("PASSERVICE__ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized with the server.
        /// </summary>
        public static string PASSERVICE__INFO_SYNCHRONIZED {
            get {
                return ResourceManager.GetString("PASSERVICE__INFO_SYNCHRONIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge with remote version required!.
        /// </summary>
        public static string PASSERVICE__WARN_NEED_MERGE {
            get {
                return ResourceManager.GetString("PASSERVICE__WARN_NEED_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized with the server. WARNING: see logs.
        /// </summary>
        public static string PASSERVICE__WARN_SYNCHRONIZED {
            get {
                return ResourceManager.GetString("PASSERVICE__WARN_SYNCHRONIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input passphrase to export &apos;{0}&apos;.
        /// </summary>
        public static string PASSEXPORT__ASK_PASSPHRASE {
            get {
                return ResourceManager.GetString("PASSEXPORT__ASK_PASSPHRASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong passphrase for &apos;{0}&apos;, try again.
        /// </summary>
        public static string PASSEXPORT__ASK_PASSPHRASE_AGAIN {
            get {
                return ResourceManager.GetString("PASSEXPORT__ASK_PASSPHRASE_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension &apos;{0}&apos; is not supported by export!.
        /// </summary>
        public static string PASSEXPORT__NOT_SUPPORTED_EXTENSION_ERR {
            get {
                return ResourceManager.GetString("PASSEXPORT__NOT_SUPPORTED_EXTENSION_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input passphrase.
        /// </summary>
        public static string PASSFILE__ASK_PASSPHRASE {
            get {
                return ResourceManager.GetString("PASSFILE__ASK_PASSPHRASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong passphrase, try input again.
        /// </summary>
        public static string PASSFILE__ASK_PASSPHRASE_AGAIN {
            get {
                return ResourceManager.GetString("PASSFILE__ASK_PASSPHRASE_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input NEW passphrase.
        /// </summary>
        public static string PASSFILE__ASK_PASSPHRASE_NEW {
            get {
                return ResourceManager.GetString("PASSFILE__ASK_PASSPHRASE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input current passphrase.
        /// </summary>
        public static string PASSFILE__ASK_PASSPHRASE_OLD {
            get {
                return ResourceManager.GetString("PASSFILE__ASK_PASSPHRASE_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string PASSFILE__BTN_CHANGE_PWD {
            get {
                return ResourceManager.GetString("PASSFILE__BTN_CHANGE_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string PASSFILE__BTN_DELETE {
            get {
                return ResourceManager.GetString("PASSFILE__BTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string PASSFILE__BTN_EXPORT {
            get {
                return ResourceManager.GetString("PASSFILE__BTN_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve conflicts....
        /// </summary>
        public static string PASSFILE__BTN_MERGE {
            get {
                return ResourceManager.GetString("PASSFILE__BTN_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string PASSFILE__BTN_OK {
            get {
                return ResourceManager.GetString("PASSFILE__BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore....
        /// </summary>
        public static string PASSFILE__BTN_RESTORE {
            get {
                return ResourceManager.GetString("PASSFILE__BTN_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PASSFILE__BTN_SAVE {
            get {
                return ResourceManager.GetString("PASSFILE__BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile decryption failed.
        /// </summary>
        public static string PASSFILE__DECRYPTION_ERROR {
            get {
                return ResourceManager.GetString("PASSFILE__DECRYPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile encryption failed.
        /// </summary>
        public static string PASSFILE__ENCRYPTION_ERROR {
            get {
                return ResourceManager.GetString("PASSFILE__ENCRYPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfiles.
        /// </summary>
        public static string PASSFILE__EXPORT_PASSFILE {
            get {
                return ResourceManager.GetString("PASSFILE__EXPORT_PASSFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open passfiles.
        /// </summary>
        public static string PASSFILE__EXPORT_PASSFILE_OPEN {
            get {
                return ResourceManager.GetString("PASSFILE__EXPORT_PASSFILE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile merged successfully!.
        /// </summary>
        public static string PASSFILE__INFO_MERGED {
            get {
                return ResourceManager.GetString("PASSFILE__INFO_MERGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase was successfully changed!.
        /// </summary>
        public static string PASSFILE__INFO_PASSPHRASE_CHANGED {
            get {
                return ResourceManager.GetString("PASSFILE__INFO_PASSPHRASE_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase was not changed!.
        /// </summary>
        public static string PASSFILE__INFO_PASSPHRASE_NOT_CHANGED {
            get {
                return ResourceManager.GetString("PASSFILE__INFO_PASSPHRASE_NOT_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed:.
        /// </summary>
        public static string PASSFILE__LABEL_CHANGED_ON {
            get {
                return ResourceManager.GetString("PASSFILE__LABEL_CHANGED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string PASSFILE__LABEL_COLOR {
            get {
                return ResourceManager.GetString("PASSFILE__LABEL_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        public static string PASSFILE__LABEL_CREATED_ON {
            get {
                return ResourceManager.GetString("PASSFILE__LABEL_CREATED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string PASSFILE__LABEL_NAME {
            get {
                return ResourceManager.GetString("PASSFILE__LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        public static string PASSFILE__LABEL_STATE {
            get {
                return ResourceManager.GetString("PASSFILE__LABEL_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed locally ({0}).
        /// </summary>
        public static string PASSFILE__STATE_LOCAL_CHANGED {
            get {
                return ResourceManager.GetString("PASSFILE__STATE_LOCAL_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New (local).
        /// </summary>
        public static string PASSFILE__STATE_LOCAL_CREATED {
            get {
                return ResourceManager.GetString("PASSFILE__STATE_LOCAL_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted locally ({0}).
        /// </summary>
        public static string PASSFILE__STATE_LOCAL_DELETED {
            get {
                return ResourceManager.GetString("PASSFILE__STATE_LOCAL_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string PASSFILE__STATE_OK {
            get {
                return ResourceManager.GetString("PASSFILE__STATE_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile &apos;{0}&apos; successfully exported to &apos;{1}&apos;.
        /// </summary>
        public static string PASSFILE__SUCCESS_EXPORT {
            get {
                return ResourceManager.GetString("PASSFILE__SUCCESS_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile &apos;{0}&apos; successfully restored from &apos;{1}&apos;.
        /// </summary>
        public static string PASSFILE__SUCCESS_RESTORE_FROM_FILE {
            get {
                return ResourceManager.GetString("PASSFILE__SUCCESS_RESTORE_FROM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile &apos;{0}&apos; successfully restored from the server.
        /// </summary>
        public static string PASSFILE__SUCCESS_RESTORE_FROM_SERVER {
            get {
                return ResourceManager.GetString("PASSFILE__SUCCESS_RESTORE_FROM_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile {0}.
        /// </summary>
        public static string PASSFILE__TITLE {
            get {
                return ResourceManager.GetString("PASSFILE__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted locally passfile {0}.
        /// </summary>
        public static string PASSFILE__TITLE_DELETED {
            get {
                return ResourceManager.GetString("PASSFILE__TITLE_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passfile {0}.
        /// </summary>
        public static string PASSFILE__TITLE_NEW {
            get {
                return ResourceManager.GetString("PASSFILE__TITLE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name!.
        /// </summary>
        public static string PASSFILE__VALIDATION__INCORRECT_NAME {
            get {
                return ResourceManager.GetString("PASSFILE__VALIDATION__INCORRECT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong passphrase!.
        /// </summary>
        public static string PASSFILE__VALIDATION__WRONG_PASSPHRASE {
            get {
                return ResourceManager.GetString("PASSFILE__VALIDATION__WRONG_PASSPHRASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string PASSFILE_COLOR__BLUE {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string PASSFILE_COLOR__GREEN {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__GREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey.
        /// </summary>
        public static string PASSFILE_COLOR__GREY {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__GREY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string PASSFILE_COLOR__ORANGE {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__ORANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string PASSFILE_COLOR__PINK {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__PINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string PASSFILE_COLOR__PURPLE {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__PURPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string PASSFILE_COLOR__RED {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        public static string PASSFILE_COLOR__TEAL {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__TEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string PASSFILE_COLOR__YELLOW {
            get {
                return ResourceManager.GetString("PASSFILE_COLOR__YELLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading error.
        /// </summary>
        public static string PASSFILE_MARK__DOWNLOAD_ERR {
            get {
                return ResourceManager.GetString("PASSFILE_MARK__DOWNLOAD_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicts are resolved .
        /// </summary>
        public static string PASSFILE_MARK__MERGED {
            get {
                return ResourceManager.GetString("PASSFILE_MARK__MERGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to resolve conflicts.
        /// </summary>
        public static string PASSFILE_MARK__NEEDS_MERGE {
            get {
                return ResourceManager.GetString("PASSFILE_MARK__NEEDS_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PASSFILE_MARK__OTHER_ERR {
            get {
                return ResourceManager.GetString("PASSFILE_MARK__OTHER_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote deleting error.
        /// </summary>
        public static string PASSFILE_MARK__REMOTE_DELETING_ERR {
            get {
                return ResourceManager.GetString("PASSFILE_MARK__REMOTE_DELETING_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading error.
        /// </summary>
        public static string PASSFILE_MARK__UPLOAD_ERR {
            get {
                return ResourceManager.GetString("PASSFILE_MARK__UPLOAD_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string PASSFILELIST__BTN_CLOSE {
            get {
                return ResourceManager.GetString("PASSFILELIST__BTN_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from the server.
        /// </summary>
        public static string PASSFILELIST__BTN_DOWNLOAD {
            get {
                return ResourceManager.GetString("PASSFILELIST__BTN_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from....
        /// </summary>
        public static string PASSFILELIST__BTN_IMPORT {
            get {
                return ResourceManager.GetString("PASSFILELIST__BTN_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string PASSFILELIST__BTN_SELECT {
            get {
                return ResourceManager.GetString("PASSFILELIST__BTN_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PASSFILELIST__COLUMN_DESCRIPTION {
            get {
                return ResourceManager.GetString("PASSFILELIST__COLUMN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string PASSFILELIST__COLUMN_FILENAME {
            get {
                return ResourceManager.GetString("PASSFILELIST__COLUMN_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actual version.
        /// </summary>
        public static string PASSFILELIST__DESCRIPTION_ACTUAL_VERSION {
            get {
                return ResourceManager.GetString("PASSFILELIST__DESCRIPTION_ACTUAL_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        public static string PASSFILELIST__DESCRIPTION_CURRENT {
            get {
                return ResourceManager.GetString("PASSFILELIST__DESCRIPTION_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to old local version.
        /// </summary>
        public static string PASSFILELIST__DESCRIPTION_LOCAL_CREATED {
            get {
                return ResourceManager.GetString("PASSFILELIST__DESCRIPTION_LOCAL_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to old version.
        /// </summary>
        public static string PASSFILELIST__DESCRIPTION_OLD_VERSION {
            get {
                return ResourceManager.GetString("PASSFILELIST__DESCRIPTION_OLD_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string PASSFILELIST__DESCRIPTION_UNKNOWN {
            get {
                return ResourceManager.GetString("PASSFILELIST__DESCRIPTION_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfiles.
        /// </summary>
        public static string PASSFILELIST__FILTER_PASSFILES {
            get {
                return ResourceManager.GetString("PASSFILELIST__FILTER_PASSFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile selection.
        /// </summary>
        public static string PASSFILELIST__TITLE {
            get {
                return ResourceManager.GetString("PASSFILELIST__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile merge.
        /// </summary>
        public static string PASSFILEMERGE__TITLE {
            get {
                return ResourceManager.GetString("PASSFILEMERGE__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input passphrase for &apos;{0}&apos;.
        /// </summary>
        public static string PASSIMPORT__ASK_PASSPHRASE {
            get {
                return ResourceManager.GetString("PASSIMPORT__ASK_PASSPHRASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong passphrase for &apos;{0}&apos;, try again.
        /// </summary>
        public static string PASSIMPORT__ASK_PASSPHRASE_AGAIN {
            get {
                return ResourceManager.GetString("PASSIMPORT__ASK_PASSPHRASE_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input NEW passphrase for passfile &apos;{0}&apos;.
        /// </summary>
        public static string PASSIMPORT__ASK_PASSPHRASE_NEW {
            get {
                return ResourceManager.GetString("PASSIMPORT__ASK_PASSPHRASE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect NEW passphrase, try again.
        /// </summary>
        public static string PASSIMPORT__ASK_PASSPHRASE_NEW_AGAIN {
            get {
                return ResourceManager.GetString("PASSIMPORT__ASK_PASSPHRASE_NEW_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile importer error! (see logs).
        /// </summary>
        public static string PASSIMPORT__ERR {
            get {
                return ResourceManager.GetString("PASSIMPORT__ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension &apos;{0}&apos; is not supported by import!.
        /// </summary>
        public static string PASSIMPORT__NOT_SUPPORTED_EXTENSION_ERR {
            get {
                return ResourceManager.GetString("PASSIMPORT__NOT_SUPPORTED_EXTENSION_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input passphrase for local version.
        /// </summary>
        public static string PASSMERGE__ASK_PASSPHRASE {
            get {
                return ResourceManager.GetString("PASSMERGE__ASK_PASSPHRASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong passphrase for LOCAL version, try again.
        /// </summary>
        public static string PASSMERGE__ASK_PASSPHRASE_AGAIN {
            get {
                return ResourceManager.GetString("PASSMERGE__ASK_PASSPHRASE_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input passphrase from other version.
        /// </summary>
        public static string PASSMERGE__ASK_PASSPHRASE_REMOTE {
            get {
                return ResourceManager.GetString("PASSMERGE__ASK_PASSPHRASE_REMOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong passphrase for OTHER version, try again.
        /// </summary>
        public static string PASSMERGE__ASK_PASSPHRASE_REMOTE_AGAIN {
            get {
                return ResourceManager.GetString("PASSMERGE__ASK_PASSPHRASE_REMOTE_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string PASSMERGE__BTN_TOOLTIP_APPLY {
            get {
                return ResourceManager.GetString("PASSMERGE__BTN_TOOLTIP_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to opposite version.
        /// </summary>
        public static string PASSMERGE__ITEM_TOOLTIP__TRANSFER {
            get {
                return ResourceManager.GetString("PASSMERGE__ITEM_TOOLTIP__TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        public static string PASSMERGE__LABEL_LOCAL {
            get {
                return ResourceManager.GetString("PASSMERGE__LABEL_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remote.
        /// </summary>
        public static string PASSMERGE__LABEL_REMOTE {
            get {
                return ResourceManager.GetString("PASSMERGE__LABEL_REMOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile local manager error! (see logs).
        /// </summary>
        public static string PASSSTORAGE__ERR {
            get {
                return ResourceManager.GetString("PASSSTORAGE__ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passfile local version not found!.
        /// </summary>
        public static string PASSSTORAGE__VERSION_NOT_FOUND_ERR {
            get {
                return ResourceManager.GetString("PASSSTORAGE__VERSION_NOT_FOUND_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommited passfile changes can be lost. Continue?.
        /// </summary>
        public static string SETTINGS__CONFIRM_SERVER_CHANGE {
            get {
                return ResourceManager.GetString("SETTINGS__CONFIRM_SERVER_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer mode.
        /// </summary>
        public static string SETTINGS__DEV_MODE {
            get {
                return ResourceManager.GetString("SETTINGS__DEV_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide passwords.
        /// </summary>
        public static string SETTINGS__HIDE_PASSWORDS {
            get {
                return ResourceManager.GetString("SETTINGS__HIDE_PASSWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is incorrect!.
        /// </summary>
        public static string SETTINGS__INCORRECT_API {
            get {
                return ResourceManager.GetString("SETTINGS__INCORRECT_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings have been saved successfully!.
        /// </summary>
        public static string SETTINGS__INFO_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("SETTINGS__INFO_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SETTINGS__LOCALIZATION {
            get {
                return ResourceManager.GetString("SETTINGS__LOCALIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SETTINGS__SAVE_BTN {
            get {
                return ResourceManager.GetString("SETTINGS__SAVE_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS__TITLE {
            get {
                return ResourceManager.GetString("SETTINGS__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input passphrase for a new passfile.
        /// </summary>
        public static string STORAGE__ASK_PASSPHRASE_FOR_NEW_PASSFILE {
            get {
                return ResourceManager.GetString("STORAGE__ASK_PASSPHRASE_FOR_NEW_PASSFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete section &apos;{0}&apos;?.
        /// </summary>
        public static string STORAGE__CONFIRM_DELETE_SECTION {
            get {
                return ResourceManager.GetString("STORAGE__CONFIRM_DELETE_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback current changes?.
        /// </summary>
        public static string STORAGE__CONFIRM_ROLLBACK {
            get {
                return ResourceManager.GetString("STORAGE__CONFIRM_ROLLBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit mode is enabled. Discard current section changes?.
        /// </summary>
        public static string STORAGE__CONFIRM_SECTION_RESET {
            get {
                return ResourceManager.GetString("STORAGE__CONFIRM_SECTION_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is copied to clipboard.
        /// </summary>
        public static string STORAGE__ITEM_INFO__PASSWORD_COPIED {
            get {
                return ResourceManager.GetString("STORAGE__ITEM_INFO__PASSWORD_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login &apos;{0}&apos; is copied to clipboard.
        /// </summary>
        public static string STORAGE__ITEM_INFO__USERNAME_COPIED {
            get {
                return ResourceManager.GetString("STORAGE__ITEM_INFO__USERNAME_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is copied to clipboard.
        /// </summary>
        public static string STORAGE__ITEM_INFO__WEBSITE_COPIED {
            get {
                return ResourceManager.GetString("STORAGE__ITEM_INFO__WEBSITE_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string STORAGE__ITEM_LABEL__PASSWORD {
            get {
                return ResourceManager.GetString("STORAGE__ITEM_LABEL__PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string STORAGE__ITEM_LABEL__WHAT {
            get {
                return ResourceManager.GetString("STORAGE__ITEM_LABEL__WHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add password.
        /// </summary>
        public static string STORAGE__ITEM_TOOLTIP__ADD {
            get {
                return ResourceManager.GetString("STORAGE__ITEM_TOOLTIP__ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string STORAGE__ITEM_TOOLTIP__DELETE {
            get {
                return ResourceManager.GetString("STORAGE__ITEM_TOOLTIP__DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string STORAGE__ITEM_TOOLTIP__GENERATE_PASSWORD {
            get {
                return ResourceManager.GetString("STORAGE__ITEM_TOOLTIP__GENERATE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy 1st.
        /// </summary>
        public static string STORAGE__ITEM_TOOLTIP__LOGIN_COPY {
            get {
                return ResourceManager.GetString("STORAGE__ITEM_TOOLTIP__LOGIN_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string STORAGE__ITEM_TOOLTIP__MOVE_DOWN {
            get {
                return ResourceManager.GetString("STORAGE__ITEM_TOOLTIP__MOVE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string STORAGE__ITEM_TOOLTIP__MOVE_UP {
            get {
                return ResourceManager.GetString("STORAGE__ITEM_TOOLTIP__MOVE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string STORAGE__ITEM_TOOLTIP__PASSWORD_COPY {
            get {
                return ResourceManager.GetString("STORAGE__ITEM_TOOLTIP__PASSWORD_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        public static string STORAGE__NO_ITEMS {
            get {
                return ResourceManager.GetString("STORAGE__NO_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sections.
        /// </summary>
        public static string STORAGE__NO_SECTIONS {
            get {
                return ResourceManager.GetString("STORAGE__NO_SECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found,
        ///try another keywords....
        /// </summary>
        public static string STORAGE__NO_SECTIONS_FOUND {
            get {
                return ResourceManager.GetString("STORAGE__NO_SECTIONS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        public static string STORAGE__PASSFILE_CONTEXT__MORE_BTN {
            get {
                return ResourceManager.GetString("STORAGE__PASSFILE_CONTEXT__MORE_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add passfile.
        /// </summary>
        public static string STORAGE__PASSFILE_TOOLTIP__ADD {
            get {
                return ResourceManager.GetString("STORAGE__PASSFILE_TOOLTIP__ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string STORAGE__RIGHT_BAR_TOOLTIP__APPLY_ITEMS {
            get {
                return ResourceManager.GetString("STORAGE__RIGHT_BAR_TOOLTIP__APPLY_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete section.
        /// </summary>
        public static string STORAGE__RIGHT_BAR_TOOLTIP__DELETE_SECTION {
            get {
                return ResourceManager.GetString("STORAGE__RIGHT_BAR_TOOLTIP__DELETE_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback.
        /// </summary>
        public static string STORAGE__RIGHT_BAR_TOOLTIP__DISCARD_ITEMS {
            get {
                return ResourceManager.GetString("STORAGE__RIGHT_BAR_TOOLTIP__DISCARD_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit section.
        /// </summary>
        public static string STORAGE__RIGHT_BAR_TOOLTIP__EDIT_ITEMS {
            get {
                return ResourceManager.GetString("STORAGE__RIGHT_BAR_TOOLTIP__EDIT_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string STORAGE__RIGHT_BAR_TOOLTIP__SAVE {
            get {
                return ResourceManager.GetString("STORAGE__RIGHT_BAR_TOOLTIP__SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string STORAGE__SECTION_LABEL__NAME {
            get {
                return ResourceManager.GetString("STORAGE__SECTION_LABEL__NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string STORAGE__SECTION_LABEL__URL {
            get {
                return ResourceManager.GetString("STORAGE__SECTION_LABEL__URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New section.
        /// </summary>
        public static string STORAGE__SECTION_NEW_NAME {
            get {
                return ResourceManager.GetString("STORAGE__SECTION_NEW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search passwords....
        /// </summary>
        public static string STORAGE__SECTION_SEARCH_INPUT_WATERMARK {
            get {
                return ResourceManager.GetString("STORAGE__SECTION_SEARCH_INPUT_WATERMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add section.
        /// </summary>
        public static string STORAGE__SECTION_TOOLTIP__ADD {
            get {
                return ResourceManager.GetString("STORAGE__SECTION_TOOLTIP__ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string STORAGE__TITLE {
            get {
                return ResourceManager.GetString("STORAGE__TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string UI__COPY {
            get {
                return ResourceManager.GetString("UI__COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string UI__CUT {
            get {
                return ResourceManager.GetString("UI__CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string UI__PASTE {
            get {
                return ResourceManager.GetString("UI__PASTE", resourceCulture);
            }
        }
    }
}
